name: convo
description: Secure chatting

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^1.6.0
  firebase_core: ^0.4.4+3
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.3
  cached_network_image: ^2.2.0+1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7
  fluttertoast: ^4.0.1
  badges: ^1.1.1
  introduction_screen: ^1.0.7
  shared_preferences: ^0.5.7+3
  encrypt: ^4.0.2
  camera: ^0.5.8+2
  path_provider: ^1.1.0
  path: ^1.6.2
  webview_flutter: ^0.3.22+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/i18n/


